### ISSUE TITLE
🛠️ Ability to resize modal with scrolling in the content

### ISSUE THREAD

**Issue by RoyvanEmpel** [takuma-ru/vue-swipe-modal#110]
### Describe the improve feature

Currently the only way to make the modal bigger / smaller is to use the header bar. Looking at IOS and some other libraries it would be nice if the user could scroll on the content to make it bigger. Once it is "fullscreen" the user should be able to scroll in the content instead of changing the modal size.

The same should happen when the user tries to scroll back up. First scrolling in the content. And when at the top the next scroll should resize the modal.

Here are a few examples of libraries that do this (Last 2 miss a fullscreen mode):
- https://js-bottomsheet-website.vercel.app/ (only functions on mobile / f12 dev mode)
- https://kadiryazici.github.io/bottom-sheet-vue3/
- https://bs.vaban.ru/

**Comment by takuma-ru** [comment]
@RoyvanEmpel

I think it is a very good idea!
We are currently using Lit to rebuild our internal logic!
I will try to implement the features you suggested during the rebuild!

**Comment by takuma-ru** [comment]
@RoyvanEmpel 
Implementation!!! (Not published yet)
Does it match the expected behavior?

https://github.com/takuma-ru/vue-swipe-modal/assets/49429291/c7249ae9-4fbc-4223-b883-65ab3c7f4755

**Comment by RoyvanEmpel** [comment]
Yes! Exactly that 😄
