### ISSUE TITLE
:sparkles: Custom header

### ISSUE THREAD

**Issue by RoyvanEmpel** [takuma-ru/vue-swipe-modal#111]
### Describe the NEW feature

Hi,

A nice improvement of the current modal would be a customizable header.

It could possibly function something like this:
```vue
<template>
  <button @click="isOpen = true">Open modal</button>

  <SwipeModal
    v-model="isOpen"
    snapPoint="auto"
  >
    <template #header>
      <SomeComponent />
    </template>

    <button @click="isOpen = false">Close modal</button>
    Modal content
  </SwipeModal>
</template>
```

This way I and other would be able to customize the header and change the visuals a bit for Android compared to IOS.

**Comment by takuma-ru** [comment]
Similar functionality has been implemented!

https://vue-swipe-modal-docs.takumaru.dev/documents/custom-style#draghandle

**Comment by takuma-ru** [comment]
@RoyvanEmpel 
Please let me know if this did not solve your issue.

**Comment by RoyvanEmpel** [comment]
Hi @takuma-ru, this is exactly what I meant! Amazing to see it added this fast.
