### ISSUE TITLE
:bug: Resizing the modal is sometimes slow / sluggish / lagging

### ISSUE THREAD

**Issue by RoyvanEmpel** [takuma-ru/vue-swipe-modal#112]
### Describe the bug

Hi,

Me and my collegues have noticed that sometimes on multiple devices and operating systems the swipe modal becomes a bit slow. It happend immediately after a reload of the page and also when the page has been open for a while.

I tried recording my screen to show it but it's barely noticable in the video:
https://github.com/takuma-ru/vue-swipe-modal/assets/47390057/6766ed7d-1722-4fa8-9112-bfe742cd2838

Is this a known issue? Or can I maybe provide some other info to figure out whats going on?

Thanks :) 

### To Reproduce

bun add @takuma-ru/vue-swipe-modal

Add the code:
```vue
<script setup>
  import { SwipeModal } from '@takuma-ru/vue-swipe-modal';
  
  const isOpen = ref(false)
</script>

<template>
  <button @click="isOpen = true">Open modal</button>
  <SwipeModal
    v-model="isOpen"
    snapPoint="30dvh"
  >
    <button @click="isOpen = false">Close modal</button>
    Modal content
  </SwipeModal>
</template>
```

This isn't the only thing in the web-app but everything else does work smooth.

### Terminal Info

- OS: IOS 17.4.1 & Android 14
- Browser: Chrome (124.0.6367.111) & Safari(latest?) & Samsung internet (25.0.0.41) & Brave
- Library version: 5.0.4
- Vue: 3.4.27

**Comment by takuma-ru** [comment]
Hi! @RoyvanEmpel! 

Indeed, I think the operation of this component is quite heavy. Especially during swiping.
A radical solution may require re-designing the logic.

As a temporary workaround, I came up with the idea of using `will-change`.
What do you think?

**Comment by RoyvanEmpel** [comment]
Hi takuma!

Maybe `will-change` can work. It is offcourse ment as a last resort when having performance problems but its a great solution without having to rework the library.
