### ISSUE TITLE
Instruction of installation for Nuxt

### ISSUE THREAD

**Issue by testteser** [takuma-ru/vue-swipe-modal#17]
Hi. Can you add the instruction for nuxt? 

Do I need to plug directly into a component or through the plugins folder? 

When I connect through the folder plugins and write a component, I am written that it is not registered. 

> [Vue warn]: Unknown custom element: <swipe-modal> - did you register the component correctly? For recursive components, make sure to provide the "name" option

Then I do the import and I get errors like:

> Invalid handler for event "mousemove": got undefined
> Invalid handler for event "mouseup": got undefined

**Comment by takuma-ru** [comment]
@testteser 
Thank you very much for your question.

<br>

> - Can you add the instruction for nuxt?

Sure!
I too have felt the need to create documentation for use with nuxt and will do so as soon as possible.
However, I have not tested this library with nuxt and it is being developed for use with vue3 and composition-api.
I think it will take some time to complete.

<br>

> - Do I need to plug directly into a component or through the plugins folder?
> - When I connect through the folder plugins and write a component, I am written that it is not registered.
> - Then I do the import and I get errors

I don't think it is necessary.
You should be able to use this library by importing it directly in the .vue file you wish to use.

This error may also be caused in part by using the library via a plugin file.
Please try the above method without using the plugin file.

The exact cause of the error will be investigated.

By the way, is the nuxt project where the error occurred published on GitHub?
If so, I would like to know the link.

**Comment by testteser** [comment]
@takuma-ru 

I've tried every method I know, but not one works. 

Still shows all the errors associated with all events in the plugin.

Sorry, but the project is not on github and I can't upload the code either (

I think if you install and try it yourself, it might show the same errors that I have.

If anything, I use Nuxt 2.

**Comment by takuma-ru** [comment]
@testteser 

I also verified this with nuxt2.

And unfortunately I got a different error than testteser.

This could be a very complicated issue.....

**Comment by takuma-ru** [comment]
@testteser 

Hi! 

Upon further investigation, it appears that this library is not available in nuxt with the current library.
Sorry ....

However, we were able to find a way to make it work with nuxt. We are currently implementing an improved version.
If you wait a little longer, you will be able to use it.

**Comment by takuma-ru** [comment]
@testteser 

Thank you for your patience.
### Now supports nuxt2.x !
Documentation will be provided at a later date.

To use it, simply create a file in the plugin folder and add the file to the plugin entry in nuxt.config.js.
