### ISSUE TITLE
Add disable swipe down action

### ISSUE THREAD

**Issue by Timur000101** [takuma-ru/vue-swipe-modal#48]
Presently, has prop **_persistent_**, that not close modal when press background. I would like add new prop like disable_modal or etc, witch not close th modal when swipe modal down.

**Comment by takuma-ru** [comment]
Great idea!
I will consider it.

**Comment by takuma-ru** [comment]
### Want to Achieve
スワイプダウンしても閉じることが出来ないようにする Prop を実装する。

### ToDo
- [ ] prop の追加
- [ ] スワイプダウンしても閉じないような処理の実装

### Directory
` このIssueで変更される予定のファイルのディレクトリ. 例) pages/index.vue `

**Comment by takuma-ru** [comment]
Done!
https://vue-swipe-modal-docs.takumaru.dev/documents/properties.html#ispersistent
