### ISSUE TITLE
Multiple Modals

### ISSUE THREAD

**Issue by compilekaiten** [takuma-ru/vue-swipe-modal#49]
### Requests

Is it possible to have multiple modals on one page?
I'm using a `v-for` to display data from my API, and want to be able to open a modal on button click for each entry that is returned. 

I'm using Vue3 and Vite ([Vitesse](https://github.com/antfu/vitesse) template)

Thanks

**Comment by takuma-ru** [comment]
HI! Thank you for question.

> Is it possible to have multiple modals on one page?

Does this mean that it is possible to display more than one modal at a time? If so, unfortunately it is not possible.

> I'm using a v-for to display data from my API, and want to be able to open a modal on button click for each entry that is 
returned.

In this case it is possible ! 
Works with vue3 + vite too! 
Please refer to the sample code below.

```vue
<template>
  <div>
    <div
      v-for="i in list"
      :key="i.title"
    >
      <button @click="i.isOpen = true">open</button>
      <swipe-modal
        v-model="i.isOpen"
        contents-height="50vh"
        border-top-radius="16px"
        dark
      >
        <p>{{ i.title }}</p>
      </swipe-modal>
    </div>
  </div>
</template>

<script lang="ts" setup>
import swipeModal from '@takuma-ru/vue-swipe-modal'

const list = ref([
  {
    isOpen: false,
    title: 'title no.1'
  },
  {
    isOpen: false,
    title: 'title no.2'
  },
  {
    isOpen: false,
    title: 'title no.3'
  },
  {
    isOpen: false,
    title: 'title no.4'
  },
])
</script>
```

**Comment by compilekaiten** [comment]
Hi. Thanks for the answer.

Your example works for me. But...

The data coming back from my Axios call is in a `ComputedRef`. I don't think it's possible to add an `isOpen: false` ref to each entry. 

I am not sure how to proceed.

**Comment by compilekaiten** [comment]
I've changed my approach to having a single modal, and populating the modal with my content using a `ref` passed on button click with my data from the API.

Thanks
