### ISSUE TITLE
Drag handler function in other parts of the component

### ISSUE THREAD

**Issue by dasturchioka** [takuma-ru/vue-swipe-modal#96]
Hi. Great job on this library! I was really in need of this kind of thing these days.

I have a question, though. When I drag holding this white button, the height of the component is changing, right? Is there any possibility of implementing this drag-handler function in other parts of the component? By saying other part, I meant any part that I start dragging the component.
![image](https://github.com/takuma-ru/vue-swipe-modal/assets/111991739/2ec8003e-ecb3-49df-965c-b5a99f133f23)

### This is working:
![exp1](https://github.com/takuma-ru/vue-swipe-modal/assets/111991739/1af734a4-7c3e-41b2-995e-26bacc2f4f30)
---
### Now I need this:
![exp2](https://github.com/takuma-ru/vue-swipe-modal/assets/111991739/0efe971f-da1b-458f-8d78-2a216c0f0feb)

Thanks for the answer!

**Comment by takuma-ru** [comment]
@dasturchioka  
Hi, dasturchioka!

The internal process is running the function you are looking for, and I think we can accommodate this by giving you access to that function.

I would implement "emit" as shown below!

```vue
<script setup lang="ts">
import { OnMoveEmitType } from "@takuma-ru/vue-swipe-modal"
// type OnMoveEmitType = {
//   movementAmountPx: number // NOTE: 100px
//   movementAmountPct: number // NOTE: 10%
// }

const handleMove = (e: OnMoveEmitType) => {
  console.log(`${e.movementAmountPx}px`)
  console.log(`${e.movementAmountPct}%`)
}
</script>

<template>
  <SwipeModal
    ...
    @move="handleMove"
  >
  ...
  </SwipeModal>
</template>
```

**Comment by dasturchioka** [comment]
Thank you for the answer @takuma-ru! I decided to build my own component for this part of the design.

**Comment by takuma-ru** [comment]
OK!
I will implement this feature either way!
